version: '3.8'

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - USERNAME=vscode
        - USER_UID=1000
        - USER_GID=1000
    volumes:
      # Main repository volume
      - ..:/workspaces/AutoGPT:cached
      # Persist dependencies and development artifacts
      - python-deps:/usr/local/lib/python3.12/site-packages/:delegated
      - node-modules:/workspaces/AutoGPT/node_modules/:delegated
      - pip-cache:/home/vscode/.cache/pip:delegated
      - npm-cache:/home/vscode/.npm:delegated
      # Git and GitHub config persistence
      - git-config:/home/vscode/.gitconfig:delegated
      - gh-config:/home/vscode/.config/gh:delegated
      # Docker socket for Docker-in-Docker
      - dind-var:/var/lib/docker:delegated
      # VS Code server extensions
      - vscode-extensions:/home/vscode/.vscode-server/extensions:delegated
    environment:
      - PYTHONPATH=/workspaces/AutoGPT
      - DOCKER_BUILDKIT=1
      - COMPOSE_DOCKER_CLI_BUILD=1
      - NODE_ENV=development
      - TERM=xterm-256color
      - COLORTERM=truecolor
    ports:
      - "8000:8000"  # Main application
      - "9229:9229"  # Node.js debugging
      - "5678:5678"  # Python debugging
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    privileged: true
    init: true
    restart: unless-stopped
    command: sleep infinity
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "[s]leep infinity", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

volumes:
  python-deps:
    name: autogpt-python-deps
  node-modules:
    name: autogpt-node-modules
  pip-cache:
    name: autogpt-pip-cache
  npm-cache:
    name: autogpt-npm-cache
  git-config:
    name: autogpt-git-config
  gh-config:
    name: autogpt-gh-config
  dind-var:
    name: autogpt-dind-var
  vscode-extensions:
    name: autogpt-vscode-extensions