version: '3.8'

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        USER_UID: 1000
        USER_GID: 1000
        USERNAME: vscode
    volumes:
      - ..:/workspaces/AutoGPT:cached
      - python-deps:/usr/local/lib/python3.12/site-packages
      - node-modules:/workspaces/AutoGPT/node_modules
      - pip-cache:/home/vscode/.cache/pip
      - npm-cache:/home/vscode/.npm
      - git-config:/home/vscode/.gitconfig
      - gh-config:/home/vscode/.config/gh
      - vscode-extensions:/home/vscode/.vscode-server/extensions
    command: sleep infinity
    environment:
      PYTHONPATH: /workspaces/AutoGPT
      NODE_ENV: development
      TERM: xterm-256color
      COLORTERM: truecolor
    ports:
      - "8000:8000"  # FastAPI
      - "9229:9229"  # Node.js debugging
      - "5678:5678"  # Python debugging
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    privileged: true
    init: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "[s]leep infinity", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

volumes:
  python-deps:
    name: autogpt-python-deps
  node-modules:
    name: autogpt-node-modules
  pip-cache:
    name: autogpt-pip-cache
  npm-cache:
    name: autogpt-npm-cache
  git-config:
    name: autogpt-git-config
  gh-config:
    name: autogpt-gh-config
  vscode-extensions:
    name: autogpt-vscode-extensions